/*
 * SPDX-License-Identifier: Apache-2.0
 */

export enum ErrorCode {
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_DID = 'INVALID_DID',
    INVALID_COMMITMENT = 'INVALID_COMMITMENT',
    DUPLICATE_IDENTITY = 'DUPLICATE_IDENTITY',
    IDENTITY_NOT_FOUND = 'IDENTITY_NOT_FOUND',
    INVALID_STATUS = 'INVALID_STATUS',
    NOOP_STATUS_TRANSITION = 'NOOP_STATUS_TRANSITION',
    REVOCATION_IS_TERMINAL = 'REVOCATION_IS_TERMINAL',
    INVALID_LIFECYCLE_TRANSITION = 'INVALID_LIFECYCLE_TRANSITION',
    INVALID_CREDENTIAL_ID = 'INVALID_CREDENTIAL_ID',
    INVALID_CREDENTIAL_TYPE = 'INVALID_CREDENTIAL_TYPE',
    INVALID_SCHEMA_ID = 'INVALID_SCHEMA_ID',
    INVALID_EXPIRATION = 'INVALID_EXPIRATION',
    DUPLICATE_CREDENTIAL = 'DUPLICATE_CREDENTIAL',
    CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND',
    UNAUTHORIZED_CREDENTIAL_TYPE = 'UNAUTHORIZED_CREDENTIAL_TYPE',
    CREDENTIAL_REVOCATION_IS_TERMINAL = 'CREDENTIAL_REVOCATION_IS_TERMINAL'
}

export class ChaincodeError extends Error {
    public readonly code: ErrorCode;

    constructor(code: ErrorCode, message: string) {
        super(`[${code}] ${message}`);
        this.name = 'ChaincodeError';
        this.code = code;
        Object.setPrototypeOf(this, ChaincodeError.prototype);
    }
}
