/*
 * SPDX-License-Identifier: Apache-2.0
 */

import { Context } from 'fabric-contract-api';

/**
 * Extracts the deterministic transaction timestamp from the Fabric transaction ChannelHeader
 * via ctx.stub.getTxTimestamp().
 *
 * This timestamp is generated by the client transaction header, validated by endorsing peers,
 * and guaranteed to be deterministic across all peer executions without relying on untrusted
 * application parameters or non-deterministic host system clocks.
 */
export function getTxTimestampISO(ctx: Context): string {
    const txTimestamp = ctx.stub.getTxTimestamp();
    const seconds = txTimestamp.seconds.low ?? (txTimestamp.seconds as unknown as number);
    const nanos = txTimestamp.nanos ?? 0;
    const milliseconds = (Number(seconds) * 1000) + Math.round(nanos / 1000000);
    return new Date(milliseconds).toISOString();
}
